version: '3.8'

services:
  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: volatile-coin-chaser-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    networks:
      - volatile-dev-network

  # Development version with hot reload
  volatile-coin-chaser-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: volatile-coin-chaser-app-dev
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      
      # Development Configuration
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - LOG_FILE=/app/logs/trading-dev.log
      
      # Trading Configuration
      - MAX_POSITIONS=5
      - MAX_RISK_PER_TRADE=0.02
      - MAX_PORTFOLIO_RISK=0.10
      - MAX_DRAWDOWN=0.05
      
      # Binance Configuration
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - BINANCE_TESTNET=true
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "3000:3000"
    networks:
      - volatile-dev-network
    command: npm run dev

volumes:
  redis_dev_data:
    driver: local

networks:
  volatile-dev-network:
    driver: bridge
